apiVersion: v1
kind: Service
metadata:
  name:  orders-service
  namespace: pisharped
spec:
  selector:
    app:  orders-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP